mkdir $HOME/ionos-coding-challenge
mkdir $HOME/ionos-coding-challenge/s3export-tool
mkdir $HOME/ionos-coding-challenge/s3export-tool/data
mkdir $HOME/ionos-coding-challenge/s3export-tool/data/minio
mkdir $HOME/ionos-coding-challenge/s3export-tool/data/elasticsearch
mkdir $HOME/ionos-coding-challenge/s3export-tool/data/mysql
mkdir $HOME/ionos-coding-challenge/s3export-tool/data/minio
mkdir $HOME/ionos-coding-challenge/s3export-tool/synchronization-batch
mkdir $HOME/ionos-coding-challenge/s3export-tool/seed-batch
mkdir $HOME/ionos-coding-challenge/s3export-tool/download-service
mkdir $HOME/ionos-coding-challenge/s3export-tool/auftraege-service
mkdir $HOME/ionos-coding-challenge/s3export-tool/kunde-service
mkdir $HOME/ionos-coding-challenge/s3export-tool/gateway-service
mkdir $HOME/ionos-coding-challenge/s3export-tool/naming-service
mkdir $HOME/ionos-coding-challenge/s3export-tool/configuration-service