version: "3.9"

services:

  rdbms-service:
    image: mysql:8.0.22
    container_name: rdbms-service
    hostname: rdbms-service
    restart: always
    user: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file="/tmp/database/s3export.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ../../../database/mysql/docker:/tmp/database
    ports:
      - 3306:3306
    networks:
      s3export:
        ipv4_address: 172.16.1.2

  cache-service:
    image: redis:3.0.5
    container_name: cache-service
    hostname: cache-service
    restart: always
    ports:
      - 6379:6379
    networks:
      s3export:
        ipv4_address: 172.16.1.3

  object-storage-service:
    image: minio/minio:RELEASE.2021-08-31T05-46-54Z.fips
    container_name: object-storage-service
    hostname: object-storage-service
    restart: always
    command: server --console-address ":4444" /home/shared
    volumes:
      - $HOME/ionos-coding-challenge/s3export-tool/data/minio:/home/shared
    ports:
      - 9000:9000
      - 4444:4444
    networks:
      s3export:
        ipv4_address: 172.16.1.4

networks:
  s3export:
    external: true
