version: "3.9"

services:

  tracing-service:
    image: openzipkin/zipkin
    container_name: tracing-service
    hostname: tracing-service
    ports:
      - 9411:9411
    networks:
      s3export:
        ipv4_address: 172.16.1.5

  #logstash-service:
  #  image: logstash:7.14.0
  #  container_name: logstash-service
  #  restart: always
  #  command: -f /tmp/config/logstash.conf
  #  volumes:
  #    - ../../../configuration/logstash:/tmp/config
  #  ports:
  #    - 4560:4560

  #elasticsearch-service:
  #  image: elasticsearch:7.14.0
  #  container_name: elasticsearch-service
  #  restart: always
  #  volumes:
  #   - $HOME/ionos-coding-challenge/s3export-tool/data/elasticsearch:/usr/share/elasticsearch/data
  #  ports:
  #    - 9200:9200

  #kibana-service:
  #  image: kibana:7.14.0
  #  container_name: kibana-service
  #  restart: always
  #  ports:
  #    - 5601:5601

networks:
  s3export:
    external: true