
#
# DATABASE AND USER RESET FOR: S3EXPORT
#


DROP USER IF EXISTS S3EXPORT_AUFTRAEGE_MGR;
DROP USER IF EXISTS S3EXPORT_KUNDE_MGR;
DROP USER IF EXISTS S3EXPORT_DOWNLOAD_MGR;
DROP USER IF EXISTS S3EXPORT_SEED_MGR;
DROP USER IF EXISTS S3EXPORT_SYNC_MGR;

TRUNCATE TABLE `S3EXPORT_AUFTRAEGE_DB`.`auftraege`;
TRUNCATE TABLE `S3EXPORT_KUNDE_DB`.`kunde`;