#
# DATABASE AND USER MANAGEMENT FOR: S3EXPORT
#


CREATE USER IF NOT EXISTS 'S3EXPORT_AUFTRAEGE_MGR'@'%' IDENTIFIED BY '!0|\|o$';
CREATE USER IF NOT EXISTS 'S3EXPORT_KUNDE_MGR'@'%' IDENTIFIED BY '!0|\|o$';
CREATE USER IF NOT EXISTS 'S3EXPORT_DOWNLOAD_MGR'@'%' IDENTIFIED BY '!0|\|o$';
CREATE USER IF NOT EXISTS 'S3EXPORT_SEED_MGR'@'%' IDENTIFIED BY '!0|\|o$';
CREATE USER IF NOT EXISTS 'S3EXPORT_SYNC_MGR'@'%' IDENTIFIED BY '!0|\|o$';

DROP DATABASE IF EXISTS S3EXPORT_AUFTRAEGE_DB;
DROP DATABASE IF EXISTS S3EXPORT_KUNDE_DB;
DROP DATABASE IF EXISTS S3EXPORT_DOWNLOAD_DB;
DROP DATABASE IF EXISTS S3EXPORT_SEED_DB;
DROP DATABASE IF EXISTS S3EXPORT_SYNC_DB;

CREATE DATABASE S3EXPORT_AUFTRAEGE_DB;
CREATE DATABASE S3EXPORT_KUNDE_DB;
CREATE DATABASE S3EXPORT_DOWNLOAD_DB;
CREATE DATABASE S3EXPORT_SEED_DB;
CREATE DATABASE S3EXPORT_SYNC_DB;

GRANT SELECT, INSERT, UPDATE ON S3EXPORT_AUFTRAEGE_DB.* TO 'S3EXPORT_AUFTRAEGE_MGR'@'%';
GRANT SELECT, INSERT, UPDATE ON S3EXPORT_KUNDE_DB.* TO 'S3EXPORT_KUNDE_MGR'@'%';
GRANT SELECT, INSERT, UPDATE ON S3EXPORT_DOWNLOAD_DB.* TO 'S3EXPORT_DOWNLOAD_MGR'@'%';
GRANT SELECT, INSERT, UPDATE ON S3EXPORT_SEED_DB.* TO 'S3EXPORT_SEED_MGR'@'%';
GRANT SELECT, INSERT, UPDATE ON S3EXPORT_SYNC_DB.* TO 'S3EXPORT_SYNC_MGR'@'%';

DROP USER IF EXISTS S3EXPORT_AUFTRAEGE_MGR;
DROP USER IF EXISTS S3EXPORT_KUNDE_MGR;
DROP USER IF EXISTS S3EXPORT_DOWNLOAD_MGR;
DROP USER IF EXISTS S3EXPORT_SEED_MGR;
DROP USER IF EXISTS S3EXPORT_SYNC_MGR;

TRUNCATE TABLE `S3EXPORT_AUFTRAEGE_DB`.`auftraege`;
TRUNCATE TABLE `S3EXPORT_KUNDE_DB`.`kunde`;