#
# DATABASE AND USER MANAGEMENT FOR: S3 EXPORT
#

CREATE USER IF NOT EXISTS 'S3EXPORT_SYNC_MGR'@'%' IDENTIFIED BY '!0|\|o$';

CREATE DATABASE IF NOT EXISTS S3EXPORT_SYNC_DB;

GRANT SELECT, INSERT, UPDATE ON S3EXPORT_SYNC_DB.* TO 'S3EXPORT_SYNC_MGR'@'%';